version: "3.8"

networks:
  test:
    driver: bridge

services:
  ubuntu:
    image: ubuntu-test
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ubuntu-ansible-test
    restart: always
    tty: true
    ports:
      - "2222:22"
      - "80:80"